swagger: '2.0'
info:
  title: Image Upload API
  description: API Gateway for uploading images to GCS
  version: 1.0.0
schemes:
  - https
paths:
  /v1/images/upload:
    post:
      summary: Upload an image
      operationId: uploadImage
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/upload-image  # Terraform deenni update chestundi
      security:
        - api_key: []
      responses:
        '202':
          description: Accepted
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"